codecov:
  # Set via secrets, see .github/workflows/tests.yml.
  token: ""
ignore:
  - "**/drivertest/*.go"
  - "samples"
coverage:
  status:
    project:
      default:
        target: 0
        threshold: null
        base: auto
    patch:
      default:
        target: 0
        threshold: null
        base: auto
